"""Brand helpers: Zioneer logo and EOL app icon.

The source images are generated by tools/generate_assets.py into assets/.
If you need to change the logo/icon, edit that script (text/color/font),
re-run it, and rebuild the app.
"""
import os

from PyQt5.QtCore import Qt
from PyQt5.QtGui import QIcon, QPixmap
from PyQt5.QtWidgets import QLabel

from app.core.paths import ICON_FILE, LOGO_FILE


def load_logo_pixmap(height=60):
    """Return a QPixmap of the Zioneer logo scaled to the given height."""
    if os.path.exists(LOGO_FILE):
        pm = QPixmap(LOGO_FILE)
        if not pm.isNull():
            return pm.scaledToHeight(height, 1)
    return QPixmap()


def load_icon():
    """Return the EOL QIcon used as the application window/taskbar icon."""
    if os.path.exists(ICON_FILE):
        icon = QIcon(ICON_FILE)
        if not icon.isNull():
            return icon
    return QIcon()


def make_logo_label(height=60, parent=None):
    """Build a QLabel showing the Zioneer logo."""
    label = QLabel(parent)
    pixmap = load_logo_pixmap(height)
    if not pixmap.isNull():
        label.setPixmap(pixmap)
        label.setFixedHeight(height)
    label.setAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
    return label
